// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXTvk47Cp1QyPYo1TdHDdbJa1RuPmK_A',
    appId: '1:917491040452:web:fcedcb53664bf98d780991',
    messagingSenderId: '917491040452',
    projectId: 'sedu-flutter-0001',
    authDomain: 'sedu-flutter-0001.firebaseapp.com',
    storageBucket: 'sedu-flutter-0001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLLunhvRfAuz1aNbVQJ8nWOM0vWbSqgY',
    appId: '1:917491040452:android:63d995e8f37813e3780991',
    messagingSenderId: '917491040452',
    projectId: 'sedu-flutter-0001',
    storageBucket: 'sedu-flutter-0001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eConUPQKfjpR0HyUIJNN3rRyV7Fu4Yk',
    appId: '1:917491040452:ios:5685744479b47c8c780991',
    messagingSenderId: '917491040452',
    projectId: 'sedu-flutter-0001',
    storageBucket: 'sedu-flutter-0001.appspot.com',
    iosBundleId: 'com.sedu.wallapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_eConUPQKfjpR0HyUIJNN3rRyV7Fu4Yk',
    appId: '1:917491040452:ios:c1ba741d9659509a780991',
    messagingSenderId: '917491040452',
    projectId: 'sedu-flutter-0001',
    storageBucket: 'sedu-flutter-0001.appspot.com',
    iosBundleId: 'com.sedu.wallapp.RunnerTests',
  );
}
